### ISSUE TITLE
Error while converting tiff images to jpg/png

### ISSUE THREAD

**Issue by slicerahul** [oliver-moran/jimp#1025]
# Expected Behavior

TIFF images could be converted into JPG or PNG

# Current Behavior

It is throwing error - JPEG error: unexpected marker ffd9

# Failure Information (for bugs)

{ JpegError
    at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:21:293
    at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:21:353
    at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:44:79
    at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:944:3
    at Object.<anonymous> (/Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:945:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/slice/work/buddysvc/Buddy_Node_App/node_modules/@jimp/tiff/dist/index.js:12:36)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
  message: 'JPEG error: unexpected marker ffd9',
  methodName: 'constructor' }

## Steps to Reproduce

Steps - 
1. Use any tiff file large than 100kb

## Context

- Jimp Version: 0.16.1
- Operating System: Mac OS
- Node version: 11.10.0

## Failure Logs

{ JpegError
at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:21:293
at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:21:353
at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:44:79
at /Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:944:3
at Object. (/Users/slice/work/buddysvc/Buddy_Node_App/node_modules/utif/UTIF.js:945:3)
at Module._compile (internal/modules/cjs/loader.js:738:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
at Module.load (internal/modules/cjs/loader.js:630:32)
at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
at Function.Module._load (internal/modules/cjs/loader.js:562:3)
at Module.require (internal/modules/cjs/loader.js:667:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (/Users/slice/work/buddysvc/Buddy_Node_App/node_modules/@jimp/tiff/dist/index.js:12:36)
at Module._compile (internal/modules/cjs/loader.js:738:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
at Module.load (internal/modules/cjs/loader.js:630:32)
message: 'JPEG error: unexpected marker ffd9',
methodName: 'constructor' }

**Comment by hipstersmoothie** [comment]
Can you provide a reproduction image?
