### ISSUE TITLE
uegent!! Fail: npm install jimp

### ISSUE THREAD

**Issue by wahengchang** [oliver-moran/jimp#111]
it s not able to install jimp on my MAC, such a good lib develop purely in javascript 

```
//**********************************************************************
//****   below is the message showed in terminal  ***************
//**********************************************************************

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jimp"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ENOSELF

npm ERR! Refusing to install jimp as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/staging/Desktop/website_/node/image_processing/jimp/npm-debug.log


//**********************************************************************
//****   below is the message in npm-debug.log ******************
//**********************************************************************

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'jimp' ]
2 info using npm@3.3.9
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData jimp
8 silly fetchNamedPackageData jimp
9 silly mapToRegistry name jimp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/jimp
13 verbose request uri https://registry.npmjs.org/jimp
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:32:53 PM
16 verbose request using bearer token for auth
17 verbose request id 425b1551e116a112
18 verbose etag "DGMOWCUX5VTCJO6CL07LSPB35"
19 http request GET https://registry.npmjs.org/jimp
20 http 304 https://registry.npmjs.org/jimp
21 verbose headers { 'cache-control': 'max-age=300',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Mon, 21 Mar 2016 08:32:54 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-sin6924-SIN',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1458549174.214151,VS0,VE200' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=300',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Mon, 21 Mar 2016 08:32:54 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-sin6924-SIN',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1458549174.214151,VS0,VE200' } ]
23 verbose etag https://registry.npmjs.org/jimp from cache
24 verbose get saving jimp to /Users/staging/.npm/registry.npmjs.org/jimp/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install jimp as a dependency of itself
42 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /Users/staging/Desktop/website_/node/image_processing/jimp
44 error Darwin 14.5.0
45 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jimp"
46 error node v5.0.0
47 error npm  v3.3.9
48 error code ENOSELF
49 error Refusing to install jimp as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by oliver-moran** [comment]
The error message appears to say that jimp is trying to install jimp as a dependency of itself:

```
npm ERR! code ENOSELF
npm ERR! Refusing to install jimp as a dependency of itself
```

How are you installing it? What command are you using? What's your set up?

Thanks.

**Comment by wahengchang** [comment]
sorry , it is my mistake, I generated a node project by express, and named it "jimp".
now I make it something else and it work pretty well .
