### ISSUE TITLE
resize breaks on negative input with unhandled exception

### ISSUE THREAD

**Issue by Narigo** [oliver-moran/jimp#151]
Adding the following line in the resize test breaks it:

```
image.clone().resize(-15, Jimp.AUTO).write("output/lenna-resize-auto.png");
```

Looking at the code in `resize.js`, it will set the target height and width to a positive value. In `index.js`, it doesn't do that and I guess that's where the break happens.

It would make sense to add a check for negative values in `index.js` as well. If there is no check, the following exception is thrown and I'm unable to catch it at all:

```
resize.js (13/14)
buffer.js:1040
    throw new TypeError('"value" argument is out of bounds');
    ^

TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1040:11)
    at Buffer.writeUInt32BE (buffer.js:1133:5)
    at Packer.packIHDR (/Users/joern/git/aggregator/lib/jimp/node_modules/pngjs/lib/packer.js:75:7)
    at PackerAsync.pack (/Users/joern/git/aggregator/lib/jimp/node_modules/pngjs/lib/packer-async.js:24:34)
    at .<anonymous> (/Users/joern/git/aggregator/lib/jimp/node_modules/pngjs/lib/png.js:58:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by oliver-moran** [comment]
Makes sense. Will add it to the backlog - or feel free to fix it and make a pull request.
