### ISSUE TITLE
Jimp contructor from JPEG Buffer ("Large" size image).

### ISSUE THREAD

**Issue by etshy** [oliver-moran/jimp#438]
Hi
I use img-scramble that use Jimp to manage file.
It works on little png files but as soon as I test with a jpeg about 700KB to 2MB (750x1300 px) It crashes.
I tracked the error and seems like it comes from this line 
`this.bitmap = JPEG.decode(data);`
The image is valid, but can't be handled by Jimp.

Here is the complete error I got

```
/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (marker was not found)
    at GridReadStream.emit (events.js:169:17)
    at GridReadStream._error (/var/www/html/rapp/node_modules/gridfs-stream/lib/readstream.js:231:8)
    at /var/www/html/rapp/node_modules/gridfs-stream/lib/readstream.js:184:28
    at err (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:414:14)
    at executeCallback (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:403:25)
    at executeOperation (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:421:7)
    at GridStore.read (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:766:10)
    at GridReadStream._push (/var/www/html/rapp/node_modules/gridfs-stream/lib/readstream.js:181:17)
    at /var/www/html/rapp/node_modules/gridfs-stream/lib/readstream.js:131:42
    at result (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:413:17)
    at executeCallback (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:405:9)
    at /var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:926:7
    at /var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:1230:7
    at result (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:413:17)
    at executeCallback (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:405:9)
    at handleCallback (/var/www/html/rapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
```

I'm quite new in the node world so I maybe made a mistake somewhere, but as it works fine with PNG but not with JPEG, I don't know what I could do wrong.

**Comment by etshy** [comment]
I still have the problem and can't get my code to work just becase of that.
My code works well on small images though.

**Comment by david476** [comment]
JPEG on that line refers to the jpeg-js package. Might be worth submitting an issue on that.

**Comment by etshy** [comment]
hmm sorry I don't remember which image I used and as I don't have to use jImp now I can't really test again.

I'll try to find the page and I'll send it if I find it.
