### ISSUE TITLE
Problem with creating image

### ISSUE THREAD

**Issue by haydenbleasel** [oliver-moran/jimp#59]
Hello,

I'm having trouble creating a blank canvas with a background colour:

```js
jimp = new Jimp(144, 144, 0xffdddddd, function (error, canvas) {
   console.log(error, canvas);
});
```

Problem is, I get this error:

```
/Users/haydenbleasel/Projects/favicons/node_modules/jimp/index.js:49
    else throw error;
         ^

Error: cb must be a function
    at Jimp.throwError (/Users/haydenbleasel/Projects/favicons/node_modules/jimp/index.js:47:43)
    at new Jimp (/Users/haydenbleasel/Projects/favicons/node_modules/jimp/index.js:91:31)
    at createImage (/Users/haydenbleasel/Projects/favicons/index.js:42:24)
    at /Users/haydenbleasel/Projects/favicons/index.js:61:21
    at Object.async.forEachOf.async.eachOf (/Users/haydenbleasel/Projects/favicons/node_modules/async/lib/async.js:233:13)
    at generateFavicons (/Users/haydenbleasel/Projects/favicons/index.js:55:19)
    at /Users/haydenbleasel/Projects/favicons/index.js:79:17
    at Object.async.forEachOf.async.eachOf (/Users/haydenbleasel/Projects/favicons/node_modules/async/lib/async.js:233:13)
    at module.exports (/Users/haydenbleasel/Projects/favicons/index.js:76:15)
    at Object.<anonymous> (/Users/haydenbleasel/Projects/favicons/test.js:3:1)
```

**Comment by haydenbleasel** [comment]
This is also probably because my colour is a string rather than a raw number-hex i.e.

```
"0xffdddddd" => 0xffdddddd
```

**Comment by haydenbleasel** [comment]
Nevermind sorry, this is the result of passing in width and height parameters that are not integers.
