### ISSUE TITLE
Error: marker was not found is crashing the server.

### ISSUE THREAD

**Issue by amirsaleem-kn** [oliver-moran/jimp#607]
```js

Error: marker was not found at decodeScan (/app/node_modules/jpeg-js/lib/decoder.js:324:15) at constructor.parse (/app/node_modules/jpeg-js/lib/decoder.js:744:29) at Object.decode (/app/node_modules/jpeg-js/lib/decoder.js:983:11) at Jimp.parseBitmap (/app/node_modules/jimp/index.js:514:36) at Jimp.loadBufferFromPath (/app/node_modules/jimp/index.js:289:29) at request (/app/node_modules/jimp/index.js:125:24) at p (/app/node_modules/jimp/src/request.js:51:21)

```
This error is causing our server to crash, proper exception handling needs to be implemented.

**Comment by hipstersmoothie** [comment]
As the PR template says:

IF YOU DO NOT FILL OUT THE FOLLOWING FORM YOUR ISSUE WILL AUTOMATICALLY BE CLOSED!!! 

Please fill out the full issue templete
