### ISSUE TITLE
marker was not found on big images 

### ISSUE THREAD

**Issue by hershyheilpern** [oliver-moran/jimp#654]
# Expected Behavior

i want to resize my image

# Current Behavior

when I try to do anything with big images I get this error

# Failure Information (for bugs)

E:\Server\Server.js:118
                                                                  if (err) throw err;
                                                                           ^

Error: marker was not found
    at decodeScan (E:\Server\node_modules\jpeg-js\lib\decoder.js:324:15)
    at Object.parse (E:\Server\node_modules\jpeg-js\lib\decoder.js:744:29)
    at Object.decode [as image/jpeg] (E:\Server\node_modules\jpeg-js\lib\decoder.js:983:11)
    at Jimp.parseBitmap (E:\Server\node_modules\@jimp\core\dist\utils\image-bitmap.js:117:53)
    at Jimp.parseBitmap (E:\Server\node_modules\@jimp\core\dist\index.js:498:32)
    at E:\Server\node_modules\@jimp\core\dist\index.js:440:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)

## Steps to Reproduce
newname = path to file

Jimp.read(newname, (err, lenna) => {
  if (err) throw err;
  lenna
	.resize(1024, Jimp.AUTO) // resize
	//.quality(60) // set JPEG quality
	//.greyscale() // set greyscale
	.write(newname); // save
});

here are the pictures I used 

![occu-lux-250-jb-bo-a](https://user-images.githubusercontent.com/12531645/48223271-accab280-e364-11e8-8268-92b1a69eb026.jpg)
![arthur_ hi_res](https://user-images.githubusercontent.com/12531645/48223272-accab280-e364-11e8-85e7-583626648486.jpg)

**Screenshots**

## Context

- Jimp Version:5.6
- Operating System: windows server 2012 R2 Standerd 
- Node version: 6.11.3

**Comment by hipstersmoothie** [comment]
Can I get your test image?

**Comment by hershyheilpern** [comment]
the 2 images that i posted on top

**Comment by hipstersmoothie** [comment]
Sorry didn’t show up in the email

**Comment by hershyheilpern** [comment]
http://1hclouds.com/temp/OCCU-LUX-250-JB-BO-A.jpg
http://1hclouds.com/temp/Arthur_(hi_res).jpg

**Comment by hershyheilpern** [comment]
did you find anything

**Comment by marceloagil** [comment]
I'm with same problem...please fix this...

**Comment by krishnaTORQUE** [comment]
I am still facing this issue `Error: marker was not found`
