### ISSUE TITLE
image.threshold is not a function

### ISSUE THREAD

**Issue by SamuelZhaoY** [oliver-moran/jimp#665]
I tried to install the plugin 'jimp/plugin-threshold', and then I followed the instruction provided by 
https://github.com/oliver-moran/jimp/tree/master/packages/plugin-threshold.  invoking method of 'image.threshold({ max: 150 });' will simply produce an error:

```
TypeError: image.threshold is not a function
    at Jimp.read (/Users/Gangdooz/private/Web/NoSmoke/temp/playground.js:23:11)
    at Timeout._onTimeout (/Users/Gangdooz/private/Web/NoSmoke/node_modules/@jimp/core/dist/index.js:331:25)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```
Version Info:

```
@jimp/plugin-threshold@0.5.5
jimp@0.5.6
```

**Comment by SamuelZhaoY** [comment]
Thanks, I found out the document for this.  Yes, the code above works 👍

**Comment by qqilihq** [comment]
@hipstersmoothie Thanks! Took me a while to find this, I then found this link:

https://github.com/oliver-moran/jimp/tree/master/packages/custom

Would probably be good to link this the “Extra Plugins” section of the readme?
