### ISSUE TITLE
Not able to run tests locally

### ISSUE THREAD

**Issue by jagaSto** [oliver-moran/jimp#742]
# Expected Behavior

I should be able to run tests locally.

# Current Behavior

They do not run successfully locally.

# Failure Information (for bugs)

when running `yarn test`, I get the following error:

```sh
/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/cli/src/cli.ts(83,17): error TS2339: Property 'terminalWidth' does not exist on type '{ (key: string, value: any, description?: string): Argv; (defaults: { [key: string]: any; }, description?: string): Argv; }'.
packages/cli/src/cli.ts(111,14): error TS2345: Argument of type '{ command: string; describe: string; builder: (yargs: Argv) => Argv; }' is not assignable to parameter of type 'CommandModule'.
  Property 'handler' is missing in type '{ command: string; describe: string; builder: (yargs: Argv) => Argv; }'.

    at createTSError (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:663:10)
    at newLoader (/jaga/code/other/jimp-fork/node_modules/pirates/lib/index.js:88:7)
    at Object.require.extensions.(anonymous function) [as .ts] (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/jaga/code/other/jimp-fork/packages/cli/test/cli.test.ts:6:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at newLoader (/jaga/code/other/jimp-fork/node_modules/pirates/lib/index.js:88:7)
    at Object.require.extensions.(anonymous function) [as .ts] (/jaga/code/other/jimp-fork/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /jaga/code/other/jimp-fork/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/jaga/code/other/jimp-fork/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/jaga/code/other/jimp-fork/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/jaga/code/other/jimp-fork/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

## Steps to Reproduce

First, I followed the instructions in the CONTRIBUTING readme, namely: 

1. `yarn install`
2. `yarn build`
3. `yarn test` --> error message

## Context

- Jimp Version: `v0.6.3`
- Operating System: macOS Mojave
- Node version: `v8.11.3`

**Comment by jagaSto** [comment]
works locally now with the CI changes.
