### ISSUE TITLE
@jimp/utils undeclared dependency error after switching to yarn v2

### ISSUE THREAD

**Issue by MikeMikhailov** [oliver-moran/jimp#876]
# Expected Behavior

Not throwing an error

# Current Behavior

Node and Yarn throw an error: 
```
UnhandledPromiseRejectionWarning: Error: @jimp/utils tried to access regenerator-runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound
```

# Failure Information (for bugs)

Appeared after switching to yarn v2 with its PnP system.

## Steps to Reproduce

1) npm install -g yarn
2) cd ~/path/to/project
3) yarn set version berry
4) yarn add -D webpack favicons-webpack-plugin

Set a build script with favicons plugin present in webpack config
Run a script
It doesn't work, with an error above

## Context

Problem appeared after switching to Yarn v2, 

- Jimp Version: @jimp/utils@0.9.8 jimp@0.9.8
- Operating System: Mac OS 10.15.4
- Node version: v13.11.0

## Failure Logs
```
(node:5069) UnhandledPromiseRejectionWarning: Error: @jimp/utils tried to access regenerator-runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: regenerator-runtime (via "regenerator-runtime/runtime")
Required by: @jimp/utils@npm:0.9.8 (via /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/)

Require stack:
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-core-npm-0.9.8-d1af0703f9-2.zip/node_modules/@jimp/core/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-custom-npm-0.9.8-646c356792-2.zip/node_modules/@jimp/custom/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/jimp-npm-0.9.8-70ac29b0f9-2.zip/node_modules/jimp/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/favicons-npm-5.5.0-3c2ef8bbd1-2.zip/node_modules/favicons/dist/helpers.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/favicons-npm-5.5.0-3c2ef8bbd1-2.zip/node_modules/favicons/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/favicons-webpack-plugin-virtual-f21eea4d15/0/cache/favicons-webpack-plugin-npm-3.0.1-81a2250f94-2.zip/node_modules/favicons-webpack-plugin/src/loader.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-2.zip/node_modules/loader-runner/lib/loadLoader.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-2.zip/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/NormalModule.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/Compiler.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/webpack.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/cli.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/bin/webpack.js
    at Object.makeError (/Users/mike/Projects/React-Template-v2/.pnp.js:16392:34)
    at resolveToUnqualified (/Users/mike/Projects/React-Template-v2/.pnp.js:23752:37)
    at resolveRequest (/Users/mike/Projects/React-Template-v2/.pnp.js:23842:27)
    at Object.resolveRequest (/Users/mike/Projects/React-Template-v2/.pnp.js:23910:26)
    at Function.module_1.Module._resolveFilename (/Users/mike/Projects/React-Template-v2/.pnp.js:23105:34)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:22990:40)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/index.js:15:1)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-core-npm-0.9.8-d1af0703f9-2.zip/node_modules/@jimp/core/dist/index.js:138:14)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-custom-npm-0.9.8-646c356792-2.zip/node_modules/@jimp/custom/dist/index.js:40:37)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/jimp-npm-0.9.8-70ac29b0f9-2.zip/node_modules/jimp/dist/index.js:10:38)
(node:5069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:5069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: @jimp/utils tried to access regenerator-runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: regenerator-runtime (via "regenerator-runtime/runtime")
Required by: @jimp/utils@npm:0.9.8 (via /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/)

Require stack:
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-core-npm-0.9.8-d1af0703f9-2.zip/node_modules/@jimp/core/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-custom-npm-0.9.8-646c356792-2.zip/node_modules/@jimp/custom/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/jimp-npm-0.9.8-70ac29b0f9-2.zip/node_modules/jimp/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/favicons-npm-5.5.0-3c2ef8bbd1-2.zip/node_modules/favicons/dist/helpers.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/favicons-npm-5.5.0-3c2ef8bbd1-2.zip/node_modules/favicons/dist/index.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/favicons-webpack-plugin-virtual-f21eea4d15/0/cache/favicons-webpack-plugin-npm-3.0.1-81a2250f94-2.zip/node_modules/favicons-webpack-plugin/src/loader.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-2.zip/node_modules/loader-runner/lib/loadLoader.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-2.zip/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/NormalModule.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/Compiler.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/lib/webpack.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/mike/Projects/React-Template-v2/.yarn/$$virtual/webpack-cli-virtual-85b02b0f0a/0/cache/webpack-cli-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/cli.js
- /Users/mike/Projects/React-Template-v2/.yarn/cache/webpack-npm-4.42.1-08435541f6-2.zip/node_modules/webpack/bin/webpack.js
    at Object.makeError (/Users/mike/Projects/React-Template-v2/.pnp.js:16392:34)
    at resolveToUnqualified (/Users/mike/Projects/React-Template-v2/.pnp.js:23752:37)
    at resolveRequest (/Users/mike/Projects/React-Template-v2/.pnp.js:23842:27)
    at Object.resolveRequest (/Users/mike/Projects/React-Template-v2/.pnp.js:23910:26)
    at Function.module_1.Module._resolveFilename (/Users/mike/Projects/React-Template-v2/.pnp.js:23105:34)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:22990:40)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-utils-npm-0.9.8-08041fe5fc-2.zip/node_modules/@jimp/utils/dist/index.js:15:1)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-core-npm-0.9.8-d1af0703f9-2.zip/node_modules/@jimp/core/dist/index.js:138:14)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/@jimp-custom-npm-0.9.8-646c356792-2.zip/node_modules/@jimp/custom/dist/index.js:40:37)
    at Module._compile (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.module_1.Module._load (/Users/mike/Projects/React-Template-v2/.pnp.js:23020:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/mike/Projects/React-Template-v2/.yarn/cache/v8-compile-cache-npm-2.0.3-e099861e3e-2.zip/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/mike/Projects/React-Template-v2/.yarn/cache/jimp-npm-0.9.8-70ac29b0f9-2.zip/node_modules/jimp/dist/index.js:10:38)
(node:5069) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 9)
```

**Comment by hipstersmoothie** [comment]
Fixed in #870
