### ISSUE TITLE
jimp.read Could not find MIME for Buffer <null> when using with busboy

### ISSUE THREAD

**Issue by aprilmintacpineda** [oliver-moran/jimp#881]
# Expected Behavior

Should not throw error on `jimp.read(myBuffer)`.

# Current Behavior

Throws error on `jimp.read(myBuffer)`.

# Failure Information (for bugs)

I don't know what to put here...

## Steps to Reproduce

I have tried it out with other images, seems not related with the image. Please see Context for more information.

**Screenshots**

N/A

## Context

I'm running jimp in a lambda function that receives an uploaded file, the form body is `multipart/form-data` that I need to parse myself, I used https://github.com/mscdex/busboy to do the job with the following code:

```js
const Busboy = require('busboy');

module.exports = function parseMultipartFormBody ({
  headers,
  body,
  isBase64Encoded
}) {
  return new Promise((resolve, reject) => {
    const parsedBody = {
      files: {}
    };
    const parser = new Busboy({ headers });

    parser.on('field', (field, value) => {
      let parsedValue = null;

      try {
        parsedValue = JSON.parse(value);
      } catch (error) {
        parsedValue = value;
      }

      parsedBody[field] = parsedValue;
    });

    parser.on('file', (field, file, name, encoding, mimetype) => {
      file.on('data', data => {
        parsedBody.files[field] = {
          data,
          size: Buffer.byteLength(data),
          name,
          encoding,
          mimetype
        };
      });
    });

    parser.on('finish', () => resolve(parsedBody));
    parser.on('error', error => reject(error));

    parser.write(body, isBase64Encoded ? 'base64' : 'binary');
    parser.end();
  });
};
```

I call it with:

```js
const {
    fullName,
    files: { profilePhoto }
  } = await parseMultipartFormData({ headers, body, isBase64Encoded });
```

the `profilePhoto` variable contains the following:

```
{
  data: <Buffer fd fd fd fd 00 10 4a 46 49 46 00 01 02 00 00 01 00 01 00 00 fd fd 00 fd 50 68 6f 74 6f 73 68 6f 70 20 33 2e 30 00 38 42 49 4d 04 04 00 00 00 00 00 fd ... 170944 more bytes>,
  size: 170994,
  name: '53086130_2309166182481943_2993533699267493888_o.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg'
}
```

then I call `jimp` like so:

```js
const jimp = require('jimp');

async function resizeProfilePhoto (fileBuffer, params) {
  const image = await jimp.read(fileBuffer);

  return image
    .contain(params.width, params.height)
    .quality(80)
    .getBufferAsync(image._originalMime);
}

// actual call located somewhere
resizeProfilePhoto(fileBuffer, { width: 140, height: 140 });
```

`jimp.read` is indeed receiving the Buffer as returned by `busboy`.

- Jimp Version: 0.10.3
- Operating System: N/A
- Node version: 12.x

## Failure Logs

```
ERROR	Error: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (/var/task/node_modules/@jimp/core/dist/utils/image-bitmap.js:187:15)
    at Jimp.parseBitmap (/var/task/node_modules/@jimp/core/dist/index.js:521:32)
    at new Jimp (/var/task/node_modules/@jimp/core/dist/index.js:474:13)
    at _construct (/var/task/node_modules/@babel/runtime/helpers/construct.js:19:21)
    at /var/task/node_modules/@jimp/core/dist/index.js:1016:32
    at new Promise (<anonymous>)
    at Function.Jimp.read (/var/task/node_modules/@jimp/core/dist/index.js:1015:10)
    at resizeProfilePhoto (/var/task/src/utils/saveProfilePhoto.js:8:28)
    at saveProfilePhoto (/var/task/src/utils/saveProfilePhoto.js:28:5)
    at module.exports.handler (/var/task/src/register.js:54:9) {
  methodName: 'constructor'
}
```

**Comment by aprilmintacpineda** [comment]
This was not an issue with jimp. I tried skipping the resize process and directly upload the image to s3 after receiving in on my lambda function. When I open the image that was uploaded, they displayed a black screen only with a square on the centre, which isn't right.

So I found this comment https://github.com/mscdex/busboy/issues/199#issuecomment-505239005 trying to fix it and then I concluded that this might also be the case for this issue and sure enough, it fixed this issue as well.
