### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es.symbol'

### ISSUE THREAD

**Issue by MBR-0001** [oliver-moran/jimp#890]
# Expected Behavior
The module doesn't cause the program to crash

# Current Behavior
The module makes the program crash

# Failure Information (for bugs)

> Error: Cannot find module 'core-js/modules/es.symbol'
Require stack:
> - C:\Users\User\Desktop\bots\node_modules\@jimp\custom\dist\index.js
> - C:\Users\User\Desktop\bots\node_modules\jimp\dist\index.js
> - C:\Users\User\Desktop\bots\test2.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Desktop\bots\node_modules\@jimp\custom\dist\index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\Desktop\\bots\\node_modules\\@jimp\\custom\\dist\\index.js',
    'C:\\Users\\User\\Desktop\\bots\\node_modules\\jimp\\dist\\index.js',
    'C:\\Users\\User\\Desktop\\bots\\test2.js'
  ]

## Steps to Reproduce

`const jimp = require('jimp');`

**Screenshots**

None
## Context

- Jimp Version: v0.11.0
- Operating System: Win 10/Win Server 2012
- Node version: 13.x

## Failure Logs
Provided above

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in `v0.12.0` :rocket:
