### ISSUE TITLE
Failing to read large files

### ISSUE THREAD

**Issue by pillowfication** [oliver-moran/jimp#915]
I'm trying to use Jimp to process images that are about 70-100 MB is size. However, I get the following error

```javascript
// image is 87.7 MB
Jimp.read('big-image', (err, img) => {
  console.log(err)
})
```

```
> Error: maxMemoryUsageInMB limit exceeded by at least 226MB
```

Is there any way around this?

**Comment by IanStewart-Celayix** [comment]
I get this issue in 0.16.0 but not 0.9.8.

**Comment by Grewamor** [comment]
same issue heare

**Comment by kde12327** [comment]
I have same problem. So I tried fix something.
[(https://developer.aliyun.com/mirror/npm/package/jpeg-js)]
On this site, there are maxMemoryUsageInMB option on decode function.

And I change \node_modules\@jimp\core\dist\utils\image-bitmap.js:196 line.

`this.bitmap = this.constructor.decoders[_mime](data);`
to
`this.bitmap = this.constructor.decoders[_mime](data, {maxMemoryUsageInMB: 2000});`

Then I can read the large image. Try this one.

**Comment by master117** [comment]
Having the same issue, 10mb jpgs turn into 1.1gb+ ram usage and crash with Error: maxMemoryUsageInMB limit exceeded

**Comment by bergiusj** [comment]
I'm having the same issue. 

Our problem has only been reported from users with a specific phone model (Huawei P30). 
We're using JIMP to compress and resize images taken from a native mobile application.

Running version:
`"jimp": "^0.16.0"`

**Comment by joelcoronah** [comment]
Same problem here, any update?

**Comment by ajitStephen** [comment]
> I get this issue in 0.16.0 but not 0.9.8.

worked for me.

**Comment by chibuike-vincent** [comment]
> I have same problem. So I tried fix something.
> [(https://developer.aliyun.com/mirror/npm/package/jpeg-js)]
> On this site, there are maxMemoryUsageInMB option on decode function.
> 
> And I change \node_modules@jimp\core\dist\utils\image-bitmap.js:196 line.
> 
> `this.bitmap = this.constructor.decoders[_mime](data);`
> to
> `this.bitmap = this.constructor.decoders[_mime](data, {maxMemoryUsageInMB: 2000});`
> 
> Then I can read the large image. Try this one.

This works locally but not working with the live app. How do I fix it

**Comment by githubBrandon** [comment]
Downgrading to 0.9.8 worked for me as well.

**Comment by zankner** [comment]
Downgrading to 0.9.8 worked as well. Is there a plan for an update?

**Comment by friddle** [comment]
if error is maxResolutionInMP limit exceeded by 36MP
 this.bitmap = this.constructor.decoders[_mime](data, {
        maxResolutionInMP:400
      });

**Comment by hisham** [comment]
You can fix by overriding the jpeg-js decoder jimp uses as follows: 

`    Jimp.decoders['image/jpeg'] = (data: Buffer) => JPEG.decode(data, { maxMemoryUsageInMB: 1024 });
`

**Comment by iwiedenm** [comment]
@hisham where do we put this code? I converted it to regular js like so

`Jimp.decoders['image/jpeg'] = (data) => JPEG.decode(data, { maxMemoryUsageInMB: 1024 })`

But I get JPEG undefined. Can you help? Thank you

**Comment by hisham** [comment]
You put it before you use any Jimp operations - i.e.: 

```
import JPEG from 'jpeg-js';

constructor() {     
Jimp.decoders['image/jpeg'] = (data: Buffer) => JPEG.decode(data, { maxMemoryUsageInMB: 1024 });
 }

myMethod(image: Buffer) {
    const jimpImage = await Jimp.read(jpegBuffer);
}
```

**Comment by 1Map** [comment]
Just a question.  How will you handle memory for 'image/tiff' images ?

Is the following correct for NodeJS ?

```
const jimpJPEG = require('jpeg-js')
const jimpTIFF = require('utif')

jimp.decoders['image/jpeg'] = (data) => {
	jimpJPEG.decode(data, {
		maxMemoryUsageInMB: 1024
	})
}
jimp.decoders['image/tiff'] = (data) => {
	var ifds = jimpTIFF.decode(data, {
		maxMemoryUsageInMB: 1024
	})
	var page = ifds[0]
	jimpTIFF.decodeImages(data, ifds)
	var rgba = jimpTIFF.toRGBA8(page)
	return {
		data: Buffer.from(rgba),
		width: page.t256[0],
		height: page.t257[0]
	}
}

```

**Comment by isikhi** [comment]
Any update? 
problem is here: node_modules/@jimp/core/dist/utils/image-bitmap.js -> node_modules/jpeg-js/lib/decoder.js

**Comment by koji98** [comment]
Having this same problem too. Is there any major difference between the 0.9 and 0.16 versions?

**Comment by tomprogers** [comment]
The solutions described here aren't working for me. They aren't even changing the output. Here's what I've got:

```
const Jimp = require('jimp')
const JPEG = require('jpeg-js')

Jimp.decoders['image/jpeg'] = (data) => {
	return JPEG.decode(data, {
		maxMemoryUsageInMB: 2048
	})
}
```

With or without this code, I get the same error:

```
throw new Error(`maxResolutionInMP limit exceeded by ${exceededAmount}MP`);
                    ^

Error: maxResolutionInMP limit exceeded by 466MP
    at constructor.parse (/Users/me/projects/my-app/node_modules/jpeg-js/lib/decoder.js:738:21)
    at Object.decode (/Users/me/projects/my-app/node_modules/jpeg-js/lib/decoder.js:1109:11)
    at Object.Jimp.decoders.image/jpeg (/Users/me/projects/my-app/src/ingest-images.js:11:14)
    at Jimp.parseBitmap (/Users/me/projects/my-app/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/Users/me/projects/my-app/node_modules/@jimp/core/dist/index.js:431:32)
    at /Users/me/projects/my-app/node_modules/@jimp/core/dist/index.js:373:15
```

I've tried 1024, 2048, even 4096. In every case, the error says the limit has been exceeded by 466MP. Since the overage value is the same in each case, I think the fix suggested here has no effect.

Any solutions?

**Comment by smirea** [comment]
same problem, still happening for 16mb jpegs

**Comment by Dakuan** [comment]
this is lots of fun with 100mb pro photos

**Comment by kane-mason** [comment]
i found the solutions above would only partially work and further transforms like `crop` would error

This is what worked for me

```js
const cachedJpegDecoder = Jimp.decoders['image/jpeg']
Jimp.decoders['image/jpeg'] = (data) => {
  const userOpts = { maxMemoryUsageInMB: 1024 }
  return cachedJpegDecoder(data, userOpts)
}
```

**Comment by kahilkubilay** [comment]
What should be the maximum size range (px or size) of an image? How can I calculate the range of image sizes?

**Comment by rcupic** [comment]
I have tried to read buffer of an 2.5MB image and got this error.

**Comment by ajitStephen** [comment]
try using https://github.com/lovell/sharp

**Comment by AnjulaS** [comment]
I just faced this today as well , is this still open or was a solution presented?

**Comment by generated** [comment]
> i found the solutions above would only partially work and further transforms like `crop` would error
> 
> This is what worked for me
> 
> ```js
> const cachedJpegDecoder = Jimp.decoders['image/jpeg']
> Jimp.decoders['image/jpeg'] = (data) => {
>   const userOpts = { maxMemoryUsageInMB: 1024 }
>   return cachedJpegDecoder(data, userOpts)
> }
> ```

@kane-mason's solution if you're using typescript you might have to add `<any>` pre  to jimp.decoders["image/jpeg"] as the default constructor only expects one argument.
```js
const cachedJpegDecoder = <any>jimp.decoders['image/jpeg']
```

**Comment by DONGXUyyds** [comment]
Have you solved your problem? I have the same problem

**Comment by lopugit** [comment]
@kane-mason genius 💯

**Comment by tamtmh** [comment]
> Have you solved your problem? I have the same problem

const cachedJpegDecoder = Jimp.decoders['image/jpeg']
Jimp.decoders['image/jpeg'] = (data) => {
  const userOpts = { maxMemoryUsageInMB: 1024 }
  return cachedJpegDecoder(data, userOpts)
}
worked for me!

**Comment by rallets** [comment]
In the latest version 1.6.0 (see [#1336](https://github.com/jimp-dev/jimp/pull/1336)) has been added the ability to specify plugin-related configuration options. 
For `image-jpeg` (based on the packages `jpeg-js`) is:
``` js
var defaultOpts = {
    // "undefined" means "Choose whether to transform colors based on the image’s color model."
    colorTransform: undefined,
    useTArray: false,
    formatAsRGBA: true,
    tolerantDecoding: true,
    maxResolutionInMP: 100, // Don't decode more than 100 megapixels
    maxMemoryUsageInMB: 512, // Don't decode if memory footprint is more than 512MB
  };
```

But I found that calling `Jimp.read` with a buffer, it will send to `jpeg-js` the options that will override the defaults.
Do use `Jimp.fromBuffer` instead.

Example:
NB. `file` is a [File](https://developer.mozilla.org/en-US/docs/Web/API/File)

This will not work, options is ignored:
```
const sourceBuffer = await file.arrayBuffer();
const image = await Jimp.read(sourceBuffer, { 'image/jpeg': { maxMemoryUsageInMB: 1 } });
```

This will work:
```
const sourceBuffer = await file.arrayBuffer();
const image = await Jimp.fromBuffer(sourceBuffer, { 'image/jpeg': { maxMemoryUsageInMB: 1 } });
```

I think this issue can be closed now.
