### ISSUE TITLE
zlib error when trying to write many things in an async function

### ISSUE THREAD

**Issue by BranchScope** [oliver-moran/jimp#929]
**Code:** 

https://pastebin.com/RZjLU1WA

**Error:**

``{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:164:17)
    at Inflate._processChunk (/home/branch/node_modules/pngjs/lib/sync-inflate.js:110:28)
    at zlibBufferSync (/home/branch/node_modules/pngjs/lib/sync-inflate.js:151:17)
    at inflateSync (/home/branch/node_modules/pngjs/lib/sync-inflate.js:155:10)
    at module.exports (/home/branch/node_modules/pngjs/lib/parser-sync.js:85:20)
    at Object.exports.read [as image/png] (/home/branch/node_modules/pngjs/lib/png-sync.js:10:10)
    at Jimp.parseBitmap (/home/branch/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/home/branch/node_modules/@jimp/core/dist/index.js:431:32)    at /home/branch/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3) errno: -5, code: 'Z_BUF_ERROR', methodName: 'constructor' }``

**Comment by mandanakhademi** [comment]
I have a similar issue. This happens randomly.

**Comment by AdamBD** [comment]
Same issue, happens randomly and cannot reliably reproduce this.
