### ISSUE TITLE
Writing text : create a buffer of a bitmap with 1bit depth with texts 

### ISSUE THREAD

**Issue by yboujraf** [oliver-moran/jimp#941]
Dear @oliver-moran, 

# Expected Behavior

I 'd like to generate a buffer of this :

- Create a bitmap of 1 bit depth (grayscale) with width : 64 and Height : 32
- Generate a text message on two lines, HORIZONTAL_ALIGN_CENTER and VERTICAL_ALIGN_MIDDLE
- Grayscale the image (to get 1 bit depth)
- Rotate -90° with keeping the size (before 64x32 - after 32x64)
- finally get the buffer (256 bytes)

# Current Behavior

```
$ node test.js
(node:9324) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Jimp.print (C:\Github\jimp\node_modules\@jimp\plugin-print\dist\index.js:224:23)
    at createTextImage (C:\Github\jimp\test.js:45:16)
(node:9324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside 
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
## Steps to Reproduce
```

IF YOUR ISSUE DEPENDS ON A PARTICULAR IMAGE BE SURE TO INCLUDE THIS AS WELL. WE CAN'T REPORDUCE IF WE DON'T HAVE YOUR IMAGE

```
const jimp = require('jimp');

async function createTextImage(
  width,
  height,
  font, {
    x = 0,
    y = 0,
    text,
    maxWidth,
    maxHeight
  }
) {
  const loadedFont = await jimp.loadFont(font);
  const image = await jimp.create(width, height, 0x00000000);

  return image.print(loadedFont, x, y, text, maxWidth, maxHeight).grayscale().rotate(-90).getBuffer(jimp.MIME_BMP, onBuffer);
}

function onBuffer(err, buffer) {
  if (err) throw err;
  console.log(buffer);
}

createTextImage(64, 32, jimp.FONT_SANS_10_BLACK, 0, 0, 'Hello\nWorld', 60, 28);

```

## Context

- Jimp Version: 0.16.1
- Operating System: win10
- Node version: 10.22.0

Best Regards

**Comment by yboujraf** [comment]
Fixed myself
