### ISSUE TITLE
TypeError: Cannot read property 'interlace' of undefined

### ISSUE THREAD

**Issue by moom0o** [oliver-moran/jimp#978]
# Expected Behavior
Should upscale the image

# Current Behavior

Fails with error
```
TypeError: Cannot read property 'interlace' of undefined
    at module.exports (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/parser-sync.js:79:16)
    at Object.exports.read [as image/png] (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/png-sync.js:10:10)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:431:32)
    at /home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}
```

# Failure Information (for bugs)

## Steps to Reproduce
Use the example code
![map](https://user-images.githubusercontent.com/48740106/104113290-1557a600-52c6-11eb-8ac1-ca221ee50d23.png)

```
            var Jimp = require('jimp');

            Jimp.read('map.png', (err, lenna) => {
                if (err) throw err;
                lenna
                    .resize(256, 256) // resize
                    .quality(70) // set JPEG quality
                    .write('upscaled.jpg'); // save
            });
```

## Context

- Jimp Version: 0.16.1
- Operating System: Debian 10
- Node version: 14.15.1

## Failure Logs
```
TypeError: Cannot read property 'interlace' of undefined
    at module.exports (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/parser-sync.js:79:16)
    at Object.exports.read [as image/png] (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/png-sync.js:10:10)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:431:32)
    at /home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}
```

**Comment by moom0o** [comment]
It was because I was reading the file while it was being written.
