### ISSUE TITLE
The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise

### ISSUE THREAD

**Issue by proginter** [oliver-moran/jimp#980]
# Expected Behavior
I need it will not kill the program because of an error I dont know why is happening

# Current Behavior
I get sometimes error, I dont know when, but it not on my code.

events.js:292
      throw er; // Unhandled 'error' event
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
    at WriteStream.Writable.write (internal/streams/writable.js:285:13)
    at WriteStream.<anonymous> (/home/XXX/domains/XXX.com/public_html/server/node_modules/@jimp/core/dist/index.js:589:18)
    at WriteStream.emit (events.js:315:20)
    at internal/fs/streams.js:380:12
    at FSReqCallback.oncomplete (fs.js:171:23)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}

# Failure Information (for bugs)
An error, it happening 1 - 2 times in a day I dont know why, but I using your library to resize and compress images.

## Steps to Reproduce

**Screenshots**

## Context

- Jimp Version: 0.13.0
- Operating System: Centos 7 64bit
- Node version: 14.15.4

## Failure Logs

Thank you!

**Comment by marinoandrea** [comment]
I am getting the same error on version `0.16.1` and node `15.8.0` while performing `Jimp.writeAsync`. 
The error must be inside some callback since try-catching does not help.

**Comment by agincel** [comment]
I'm encountering this same issue.

**Comment by WannaBeChay** [comment]
Same issue.

**Comment by TunjiDev** [comment]
Same issue, how do we resolve this pls?

**Comment by WannaBeChay** [comment]
U are talking about, my problem on stackoverflow ?

Em ter., 3 de ago. de 2021 às 11:27, Igbatayo Adetunji <
***@***.***> escreveu:

**Comment by flixcheck** [comment]
We're getting the same error on version `0.16.1` with several files. Since these are files of our customers which are – in the case of an error – deleted immediately due to security considerations, we cannot provide the files to reproduce the error. This is the stack trace:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
    at validChunk (_stream_writable.js:281:10)
    at WriteStream.Writable.write (_stream_writable.js:316:21)
    at WriteStream.<anonymous> (/app/node_modules/@jimp/core/dist/index.js:589:18)
    at WriteStream.emit (events.js:314:20)
    at WriteStream.EventEmitter.emit (domain.js:483:12)
    at internal/fs/streams.js:366:10
    at FSReqCallback.oncomplete (fs.js:156:23)'
```

**Comment by ivatov** [comment]
I encountered this when trying to read, manipulate and eventually write every image from a given collection of images . What I did to workaround it:
```
import { writeFile } from 'node:fs/promises';
import jimp from 'jimp';

// given `imgName` and `imgPath`:
const jimpImg = await jimp.read(imgPath);
// do whatever you like with jimpImg
const imgData = await jimpImg.getBufferAsync(jimp.AUTO);
await writeFile(imgName, imgData);
```

**Comment by stevezac-osu** [comment]
Hi there.  I've just added a pull request to resolve this issue.  When I tested this issue, I was only able to recreate this when encoding as a GIF.  Upon inspection, it looks like the GIF type encoder returns a Promise, whereas the other types return strings or buffers.  This is especially difficult for the write function, which opened a stream and wrote the buffer to the stream.  For GIFs, that meant the write function was trying to write a promise to the stream, which is what was throwing the error.

The commit I made _should_ resolve the issue.  Please let me know if this doesn't solve the issue for everyone.
